# Generated by Django 3.1.5 on 2021-02-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210205_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('cathegory', models.CharField(choices=[('Food', 'Food'), ('Food Item', 'Food Item')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('lable', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2, null=True)),
                ('slug', models.SlugField()),
                ('tag', models.ManyToManyField(to='store.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AlterField(
            model_name='product',
            name='cathegory',
            field=models.CharField(choices=[('G', 'Goods'), ('S', 'Services')], max_length=200, null=True),
        ),
    ]
