# Generated by Django 3.1.5 on 2021-02-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_auto_20210205_1650'),
        ('store', '0003_auto_20210205_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.agent'),
        ),
    ]
