# Generated by Django 3.1.5 on 2021-01-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210126_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
