# Generated by Django 3.1.5 on 2021-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210127_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lable',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=2),
        ),
    ]
