# Generated by Django 3.1.5 on 2021-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_lable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lable',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('D', 'Danger')], default='P', max_length=2),
        ),
    ]
