# Generated by Django 3.1.5 on 2021-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210127_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lable',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('D', 'Danger')], max_length=2, null=True),
        ),
    ]
