# Generated by Django 3.1.5 on 2021-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210127_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lable',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2, null=True),
        ),
    ]
