# Generated by Django 3.1.5 on 2021-01-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210127_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='items',
        ),
    ]
