# Generated by Django 3.1.5 on 2021-01-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210127_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='product',
        ),
    ]
