# Generated by Django 3.1.5 on 2021-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone1', models.IntegerField(null=True)),
                ('phone2', models.IntegerField(blank=True, null=True)),
                ('town', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=50)),
                ('agent_type', models.CharField(blank=True, max_length=50)),
                ('bike', models.BooleanField(default=False)),
                ('keke', models.BooleanField(default=False)),
                ('car', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.CharField(max_length=200, null=True)),
                ('phone2', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_id', models.CharField(max_length=10, null=True)),
                ('sex', models.CharField(max_length=70, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('apartment_address', models.CharField(max_length=200, null=True)),
                ('street_address', models.CharField(max_length=200, null=True)),
                ('phone1', models.CharField(max_length=200, null=True)),
                ('phone2', models.CharField(max_length=200, null=True)),
                ('business_name', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('goods', models.BooleanField(default=False)),
                ('services', models.BooleanField(default=False)),
                ('skill', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=10, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
