# Generated by Django 3.1.5 on 2021-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='client',
        ),
        migrations.AddField(
            model_name='item',
            name='client',
            field=models.ManyToManyField(to='staffs.Client'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ManyToManyField(to='staffs.Vendor'),
        ),
    ]
