# Generated by Django 3.1.5 on 2021-02-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_auto_20210205_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='town',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
