# Generated by Django 3.1.5 on 2021-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_auto_20210205_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
