# Generated by Django 3.1.5 on 2021-02-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_auto_20210208_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='address',
            new_name='apartment_address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='business_type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='goods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='street_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sex',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
