# Generated by Django 3.1.5 on 2021-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_auto_20210208_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
