# Generated by Django 3.1.5 on 2021-03-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_auto_20210308_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(),
        ),
    ]
