# Generated by Django 3.1.5 on 2021-02-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_auto_20210209_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_id',
            new_name='agent_type',
        ),
    ]
