# Generated by Django 3.1.5 on 2021-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_auto_20210209_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
