# Generated by Django 3.1.5 on 2021-02-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_agent_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.agent'),
        ),
    ]
