# Generated by Django 3.1.5 on 2021-02-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_client_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
