# Generated by Django 3.1.5 on 2021-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0011_auto_20210209_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
