# Generated by Django 3.1.5 on 2021-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0012_client_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agent_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
