# Generated by Django 3.1.5 on 2021-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vpaid',
            field=models.BooleanField(default=False),
        ),
    ]
