# Generated by Django 3.1.5 on 2021-04-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210420_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='seller',
        ),
    ]
