# Generated by Django 3.1.5 on 2021-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210528_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thubnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
