# Generated by Django 3.1.5 on 2021-04-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_useraccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_code',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
