# Generated by Django 3.1.5 on 2021-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_fastfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastfood',
            name='menu',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='menu',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
