# Generated by Django 3.1.5 on 2021-04-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210422_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
