# Generated by Django 3.1.5 on 2021-06-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
    ]
