# Generated by Django 3.1.5 on 2021-06-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastfood',
            name='menu',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='food',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='store.fastfood'),
            preserve_default=False,
        ),
    ]
