# Generated by Django 3.1.5 on 2021-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210607_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('G', 'Goods'), ('S', 'Services'), ('FS', 'FastFood')], max_length=10),
        ),
    ]
