# Generated by Django 3.1.5 on 2021-04-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210422_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Codebox',
        ),
    ]
