# Generated by Django 3.1.5 on 2021-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210607_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
