# Generated by Django 3.1.5 on 2021-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210617_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
