# Generated by Django 3.1.5 on 2021-04-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210422_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
