# Generated by Django 3.1.5 on 2021-04-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_userprofile_bus_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='agent',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='seller',
            new_name='is_seller',
        ),
    ]
