# Generated by Django 3.1.5 on 2021-07-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210708_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensis',
            options={'verbose_name_plural': 'Expensis'},
        ),
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=11, upload_to='product'),
            preserve_default=False,
        ),
    ]
