# Generated by Django 3.1.5 on 2021-07-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210709_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bus_account',
        ),
    ]
