# Generated by Django 3.1.5 on 2021-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210425_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invest_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sav_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
