# Generated by Django 3.1.5 on 2021-07-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_delete_seller'),
        ('store', '0018_remove_userprofile_bus_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('fast_food', models.BooleanField(default=False)),
                ('goods', models.BooleanField(default=False)),
                ('services', models.BooleanField(default=False)),
                ('skill', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover')),
                ('agent_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userprofile')),
            ],
        ),
    ]
