# Generated by Django 3.1.5 on 2021-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_seller_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('FREE', 'FREE'), ('ON SALE', 'ON SALE'), ('NOT ON SALE', 'NOT ON SALE'), ('HOT', 'HOT')], default='NEW', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.BooleanField(default=False),
        ),
    ]
