# Generated by Django 3.1.5 on 2021-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210505_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
