# Generated by Django 3.1.5 on 2021-05-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210505_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_type', models.CharField(choices=[('T', 'Top Up'), ('S', 'Save'), ('W', 'Whitdraw')], max_length=10)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('debited', models.BooleanField()),
                ('credited', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.useraccount')),
            ],
        ),
    ]
