# Generated by Django 3.1.5 on 2021-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='ads')),
                ('slug', models.SlugField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('B', 'Big'), ('S', 'Small')], max_length=10)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
