# Generated by Django 3.1.5 on 2021-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('T', 'Top Up'), ('W', 'Withdrawal'), ('SV', 'Save'), ('SE', 'Send')], max_length=20),
        ),
    ]
