# Generated by Django 3.1.5 on 2021-05-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_transaction_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='account',
        ),
    ]
