# Generated by Django 3.1.5 on 2021-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210506_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
