# Generated by Django 3.1.5 on 2021-08-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210809_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='town',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
