# Generated by Django 3.1.5 on 2021-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210507_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debited',
            field=models.BooleanField(default=False),
        ),
    ]
