# Generated by Django 3.1.5 on 2021-08-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_seller_town'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
