# Generated by Django 3.1.5 on 2021-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_delete_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Topup', 'Top Up'), ('Withdrawal', 'Withdrawal'), ('Save', 'Save'), ('Send', 'Send')], max_length=20),
        ),
    ]
