# Generated by Django 3.1.5 on 2021-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210507_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('T', 'Top Up'), ('W', 'Withdrawal'), ('SV', 'Save')], max_length=20),
        ),
    ]
