# Generated by Django 3.1.5 on 2021-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210507_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='invest_balance',
            new_name='flex_balance',
        ),
    ]
