# Generated by Django 3.1.5 on 2021-05-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210507_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ref_code', models.CharField(max_length=30)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.useraccount')),
            ],
        ),
    ]
