# Generated by Django 3.1.5 on 2021-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210818_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Ussd', 'Ussd'), ('Online', 'Online')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
