# Generated by Django 3.1.5 on 2021-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_topupfund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='credited',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debited',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit'), ('P', 'Pending')], default='Pending', max_length=10),
        ),
    ]
