# Generated by Django 3.1.5 on 2021-08-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_order_store_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='store_record',
            field=models.BooleanField(default=False),
        ),
    ]
