# Generated by Django 3.1.5 on 2021-05-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210507_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('D', 'Debited'), ('C', 'Credited'), ('P', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='TopupConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_ref', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.useraccount')),
            ],
        ),
    ]
