# Generated by Django 3.1.5 on 2021-05-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210507_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('T', 'Top Up'), ('W', 'Withdrawal'), ('SV', 'Save'), ('SE', 'Send')], max_length=20),
        ),
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Mek', 'Mek Wallet'), ('Other', 'Other Bank')], max_length=10)),
                ('amount', models.FloatField()),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('trans_ref', models.CharField(max_length=200)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.useraccount')),
            ],
        ),
    ]
