# Generated by Django 3.1.5 on 2021-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_transactions_store_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Wallet', 'Wallet'), ('Ussd', 'Ussd'), ('Online', 'Online')], max_length=10),
        ),
    ]
