# Generated by Django 3.1.5 on 2021-05-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20210509_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupconfirm',
            name='amount',
            field=models.FloatField(default=33),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topupconfirm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userprofile'),
        ),
    ]
