# Generated by Django 3.1.5 on 2021-08-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20210819_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('value_price', models.CharField(blank=True, max_length=100, null=True)),
                ('item_location', models.CharField(max_length=200)),
                ('delivery_address', models.CharField(max_length=200)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_number', models.IntegerField()),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_number', models.IntegerField()),
                ('delivery_charge', models.FloatField()),
                ('ref', models.CharField(max_length=50)),
                ('collect_payment', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Logistics',
            },
        ),
    ]
