# Generated by Django 3.1.5 on 2021-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='receiver_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logistics',
            name='sender_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
