# Generated by Django 3.1.5 on 2021-05-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210511_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topupconfirm',
            old_name='user',
            new_name='approved_by',
        ),
    ]
