# Generated by Django 3.1.5 on 2021-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20210823_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
