# Generated by Django 3.1.5 on 2021-05-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_saving_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.userprofile'),
        ),
        migrations.DeleteModel(
            name='TopupFund',
        ),
    ]
