# Generated by Django 3.1.5 on 2021-08-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20210823_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.CreateModel(
            name='Tashcan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('store_record', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.useraccount')),
            ],
        ),
    ]
