# Generated by Django 3.1.5 on 2021-08-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20210825_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tashcan',
            new_name='Trashcan',
        ),
    ]
