# Generated by Django 3.1.5 on 2021-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20210825_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='tel_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='tel_two',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
