# Generated by Django 3.1.5 on 2021-02-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_code', models.CharField(blank=True, default=101, max_length=10, null=True)),
                ('agent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bike', models.BooleanField(default=False)),
                ('keke', models.BooleanField(default=False)),
                ('car', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.CharField(max_length=200, null=True)),
                ('phone2', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('apartment_address', models.CharField(max_length=200, null=True)),
                ('land_mark', models.CharField(max_length=200, null=True)),
                ('client_code', models.CharField(max_length=10, null=True)),
                ('agent_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(max_length=70, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/cover/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('goods', models.BooleanField(default=False)),
                ('services', models.BooleanField(default=False)),
                ('skill', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vendor_code', models.CharField(blank=True, default=102, max_length=10, null=True)),
                ('agent_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.agent')),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.client')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.client'),
        ),
    ]
