# Generated by Django 3.1.5 on 2021-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20210607_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('porpurse', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
