# Generated by Django 3.1.5 on 2021-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_itemtags_vendoritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
