# Generated by Django 3.1.5 on 2021-02-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_vendoritem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='vendoritem',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.vendoritem'),
        ),
    ]
