# Generated by Django 3.1.5 on 2021-07-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_auto_20210712_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
