# Generated by Django 3.1.5 on 2021-08-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='status',
        ),
        migrations.AddField(
            model_name='advert',
            name='display_section',
            field=models.CharField(choices=[('Big', 'Big'), ('Small', 'Small')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
