# Generated by Django 3.1.5 on 2021-04-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_auto_20210308_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='product',
        ),
    ]
