# Generated by Django 3.1.5 on 2021-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_remove_vendor_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoritem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='vpayment',
            name='seller',
        ),
        migrations.AddField(
            model_name='vendor',
            name='amount',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ItemTags',
        ),
        migrations.DeleteModel(
            name='VendorItem',
        ),
        migrations.DeleteModel(
            name='Vpayment',
        ),
    ]
