# Generated by Django 3.1.5 on 2021-04-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_auto_20210420_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='info',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='info',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
