# Generated by Django 3.1.5 on 2021-04-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0011_auto_20210422_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_code',
        ),
    ]
